### ISSUE TITLE
Error while copying store paths to image

### ISSUE THREAD

**Issue by dsferruzza** [Robertof/nixos-docker-sd-image-builder#1]
Hi!

This project seems very promising and your blog post is very nice, so thank you!

While trying to make it work as-is (I just updated the SSH key), everything seems to work fine until I get the following error:

```
build-nixos_1   | building '/nix/store/j6w1im36k9dgn44clb3f8bh43da9y6cy-ext4-fs.img.zst.drv'...
build-nixos_1   | Creating an EXT4 image of 2854793216 bytes (numInodes=95866, numDataBlocks=505239)
build-nixos_1   | mke2fs 1.45.5 (07-Jan-2020)
build-nixos_1   | Discarding device blocks: done
build-nixos_1   | Creating filesystem with 696971 4k blocks and 174592 inodes
build-nixos_1   | Filesystem UUID: 44444444-4444-4444-8888-888888888888
build-nixos_1   | Superblock backups stored on blocks:
build-nixos_1   |         32768, 98304, 163840, 229376, 294912
build-nixos_1   |
build-nixos_1   | Allocating group tables: done
build-nixos_1   | Writing inode tables: done
build-nixos_1   | Creating journal (16384 blocks): done
build-nixos_1   | Writing superblocks and filesystem accounting information: done
build-nixos_1   |
build-nixos_1   | copying store paths to image...
build-nixos_1   | /nix/store/690a5swp0j228wx5snj3izs0zayd967l-stdenv-linux/setup: line 1299:  6752 Killed                  cptofs -t ext4 -i $img $storePaths /nix/store/
build-nixos_1   | builder for '/nix/store/j6w1im36k9dgn44clb3f8bh43da9y6cy-ext4-fs.img.zst.drv' failed with exit code 137
build-nixos_1   | cannot build derivation '/nix/store/vxca84dr6k2xqsg78wdx2qlszm8v9kz5-nixos-sd-image-20.03post-git-aarch64-linux.img.drv': 1 dependencies couldn't be built
```

I'm using the latest Docker Toolbox on Windows 10:

```
Docker version 19.03.1, build 74b1e89e8a
docker-compose version 1.24.1, build 4667896b
```

I tried to put 2 GB of RAM (instead of 1) in the VM (Docker Toolbox runs Docker inside a VirtualBox VM), but nothing changed.

Any idea of what could be wrong or how to investigate?

**Comment by Robertof** [comment]
Hey there! Thanks for the kind words, and I am very happy that this is useful for you!

That definitely looks like an out-of-memory error. Specifically, the kernel is brutally killing `cptofs` as it was the process causing the actual OOM.

Unfortunately `cptofs` isn't very well designed and takes up loads of memory. In my testing, its memory usage at one point reached 8 GiB of used RAM.

So here are a few solutions:
- add a few gigabytes of swap. This is definitely the easiest way -- it will take a bit longer to build but it will work.
- there is a patch in review on the `nixpkgs` repo (https://github.com/NixOS/nixpkgs/pull/82718) which replaces `cptofs` with a more efficient tool. You can apply this relatively easily by editing the [`docker/build-nixos/setup-image-user.sh`](https://github.com/Robertof/nixos-docker-sd-image-builder/blob/master/docker/build-nixos/setup-image-user.sh#L29) file and adding before `echo "image is ready"` the following:
  ```sh
  curl -L "https://github.com/NixOS/nixpkgs/pull/82718.patch" | git apply
  ```
  afterwards, just execute `./run.sh up --build` which makes sure that the container is rebuilt. I will probably make a commit to this repo to replace the resize2fs patch with this one as it also fixes the other issue.

Let me know if you have any questions or further issues!

Thanks again!
Roberto

**Comment by dsferruzza** [comment]
I tried the second solution: build completes successfully!

But then after flashing on my RPi 4B, it does not boot. The RPi seems stuck on the rainbow screen so I assume it does not find what to boot and maybe NixOS/nixpkgs#82718 broke something here(?)

For the record, here is what I did:

```diff
diff --git a/docker/build-nixos/setup-image-user.sh b/docker/build-nixos/setup-image-user.sh
index 0dabae1..e965c94 100644
--- a/docker/build-nixos/setup-image-user.sh
+++ b/docker/build-nixos/setup-image-user.sh
@@ -26,4 +26,6 @@ if [ -n "${APPLY_RESIZE2FS_PATCH+x}" ]; then
   curl -L "https://github.com/NixOS/nixpkgs/pull/86366.patch" | git apply
 fi

+curl -L "https://github.com/NixOS/nixpkgs/pull/82718.patch" | git apply
+
 echo "image is ready"
```

**Comment by Robertof** [comment]
Glad that it solved the initial issue!

The reason why it's not working is because NixOS defaults to build for Raspberry Pi 3s, as [it's the RPi NixOS has first-class support for](https://nixos.wiki/wiki/NixOS_on_ARM/Raspberry_Pi).

I do actually have in the pipeline to include first-class support for building for an RPi 4 to this repo (and to make it clear) -- however, it should be fairly easy to do it manually! Bear with me.

Create a new file in `config` named `sd-image-raspberrypi4.nix` with the following contents:

```nix
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/profiles/base.nix>
    <nixpkgs/nixos/modules/profiles/installation-device.nix>
    <nixpkgs/nixos/modules/installer/cd-dvd/sd-image.nix>
  ];

  boot.loader.grub.enable = false;
  boot.loader.raspberryPi.enable = true;
  boot.loader.raspberryPi.version = 4;
  boot.kernelPackages = pkgs.linuxPackages_rpi4;

  boot.consoleLogLevel = lib.mkDefault 7;

  sdImage = {
    firmwareSize = 128;
    # This is a hack to avoid replicating config.txt from boot.loader.raspberryPi
    populateFirmwareCommands =
      "${config.system.build.installBootLoader} ${config.system.build.toplevel} -d ./firmware";
    # As the boot process is done entirely in the firmware partition.
    populateRootCommands = "";
  };

  # the installation media is also the installation target,
  # so we don't want to provide the installation configuration.nix.
  installer.cloneConfig = false;
}
```

(this is just the [upstream file](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/sd-image-raspberrypi4.nix) with relative paths replaced)

Then, open [`config/sd-card.nix`](https://github.com/Robertof/nixos-docker-sd-image-builder/blob/master/config/sd-card.nix) and replace this (line 3):

```nix
    <nixpkgs/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix>
```

with:

```nix
    ./sd-image-raspberrypi4.nix
```

so that the first few lines look like:

```nix
{ lib, ... }: {
  imports = [
    ./sd-image-raspberrypi4.nix
  ];
  ...
```

That should be enough! `./run.sh` should now produce an RPi 4 compatible image.

**Comment by ccamrobertson** [comment]
@Robertof first and foremost, thanks for this fantastic tool.

I've been following this issue as I encountered both of @dsferruzza's problems; the first error -- https://github.com/Robertof/nixos-docker-sd-image-builder/issues/1#issue-617567046 -- was while attempting to build on OS X. 

Prior to seeing this issue I assumed that this was a `binfmt_misc` host issue due to OS X, so I tried on an Ubuntu 18.04 box. The image built successfully there, but would not boot; as above, I too need an image for the Raspberry Pi 4.

I've implemented the changes above for the Raspberry Pi 4 as well as the patch for `cptofs`. Then, for good measure I upped the ram available to Docker on my Mac to 8gb.

Unfortunately on both platforms I'm now seeing the following error:

```
build-nixos_1   | building '/nix/store/a99h8048dx5msylk3iq7347ga5jvyli6-stage-1-init.sh.drv'...
build-nixos_1   | checking syntax
build-nixos_1   | building '/nix/store/l21wfl7fhjn0hgn74xgwykpqpal52v0n-initrd-linux-4.19.75-1.20190925.drv'...
build-nixos_1   | 40865 blocks
build-nixos_1   | building '/nix/store/nmsc3h24hw6i1s0rg80qvwymwrcdqayr-nixos-system-nixos-20.03post-git.drv'...
build-nixos_1   | building '/nix/store/r94fa0qxd5wmzd6nxdpc3qd7c49hlmx1-closure-info.drv'...
build-nixos_1   | building '/nix/store/xc36xpc8j8b2qb9frfk2gx4yqw8a4y3j-ext4-fs.img.zst.drv'...
build-nixos_1   | preparing store paths for image...
build-nixos_1   | /nix/store/62l1fmmmynxr5q8jc65wllk9wl2fmnp3-coreutils-8.31/bin/cp: missing file operand
build-nixos_1   | Try '/nix/store/62l1fmmmynxr5q8jc65wllk9wl2fmnp3-coreutils-8.31/bin/cp --help' for more information.
build-nixos_1   | builder for '/nix/store/xc36xpc8j8b2qb9frfk2gx4yqw8a4y3j-ext4-fs.img.zst.drv' failed with exit code 1
build-nixos_1   | cannot build derivation '/nix/store/0kli6nixlvzdffpvgf2hxsan1d81mk3h-nixos-sd-image-20.03post-git-aarch64-linux.img.drv': 1 dependencies couldn't be built
build-nixos_1   | error: build of '/nix/store/0kli6nixlvzdffpvgf2hxsan1d81mk3h-nixos-sd-image-20.03post-git-aarch64-linux.img.drv' failed
cleanup-qemu_1  | connect to [::ffff:172.18.0.2]:11111 from docker_build-nixos_1.docker_default:39973 ([::ffff:172.18.0.3]:39973)
cleanup-qemu_1  | build done
cleanup-qemu_1  | binfmt: detected x86 architecture, proceeding
cleanup-qemu_1  | binfmt: clearing existing entry for qemu-aarch64-docker-nixos
cleanup-qemu_1  | binfmt: cleanup done
docker_cleanup-qemu_1 exited with code 0
docker_build-nixos_1 exited with code 100
```

The full build log for the Ubuntu machine is available at https://gist.github.com/ccamrobertson/fada537b9886087fb21e5ec3bf3ad9c8; it looks like there is something up with `cp`, but I'm not going to have the chance to inspect the Dockers more closely for a bit.

**Comment by Robertof** [comment]
Hi @ccamrobertson - first, apologies for the issues you're having, I envisioned this being painless for everyone but I clearly did my math wrong!

So your error looks quite interesting! I've never had it before, and I had many. It looks like it's failing on one of these two lines [here](https://github.com/NixOS/nixpkgs/blob/f192676d60854f7041b8c98a3cd686b509cc7a9d/nixos/lib/make-ext4-fs.nix#L46-L48):

```sh
      echo "preparing store paths for image..."
      cp -a $(cat ${sdClosureInfo}/store-paths) -t ./rootImage/nix/store/
      cp -a ./files/* -t ./rootImage/
```

which is very weird. Would you mind re-running the build with `./run.sh up --force-recreate`?

Also, can you paste the exact contents of your `*.nix` files (minus any SSH key)? I want to try to reproduce it locally.

Thank you!

**Comment by Robertof** [comment]
I will dedicate some time this evening to set up this repo to also build RPi 4 images. 

Unfortunately I don't have a Pi 4 so it's a bit difficult to test the actual output, and it looks like the main issue is that the RPi 4, unlike the 3, does not boot on the mainline Linux kernel. This is because the RPi kernel has some patches applied on top of it and some of them still have to be upstreamed. In addition to this, U-Boot, which is used as the base for NixOS ARM builds, [does not work on it yet](https://github.com/NixOS/nixpkgs/pull/87244) (see also [this](https://github.com/NixOS/nixpkgs/pull/70796)). That's the reason why a custom builder is required -- it avoids using U-Boot and uses the latest (official) RPi 4 kernel.

I'm wondering if I should integrate the following patches:
- https://github.com/NixOS/nixpkgs/pull/78090 which should fix potential issues with config reloads not working
- https://gitlab.com/diamondburned/nix-rpi4 as the base config which looks promising

**Comment by ccamrobertson** [comment]
@Robertof no problem, thank you for taking a moment to take a look. I'm re-running the build with `./run.sh up --force-recreate`, although I should note that I've previously removed all the Docker images and containers between builds.

`sd-card.nix`:
```
{ lib, ... }: {
  imports = [
    ./sd-image-raspberrypi4.nix
  ];
  # The installer starts with a "nixos" user to allow installation, so add the SSH key to
  # that user. Note that the key is, at the time of writing, put in `/etc/ssh/authorized_keys.d`
  users.extraUsers.nixos.openssh.authorizedKeys.keys = [
    "ssh-rsa ..."
  ];
  # bzip2 compression takes loads of time with emulation, skip it. Enable this if you're low
  # on space.
  sdImage.compressImage = false;
  # OpenSSH is forced to have an empty `wantedBy` on the installer system[1], this won't allow it
  # to be automatically started. Override it with the normal value.
  # [1] https://github.com/NixOS/nixpkgs/blob/9e5aa25/nixos/modules/profiles/installation-device.nix#L76
  systemd.services.sshd.wantedBy = lib.mkOverride 40 [ "multi-user.target" ];
  # Enable OpenSSH out of the box.
  services.sshd.enabled = true;
}

```

and `sd-image-raspberrypi4.nix`:
```
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/profiles/base.nix>
    <nixpkgs/nixos/modules/profiles/installation-device.nix>
    <nixpkgs/nixos/modules/installer/cd-dvd/sd-image.nix>
  ];

  boot.loader.grub.enable = false;
  boot.loader.raspberryPi.enable = true;
  boot.loader.raspberryPi.version = 4;
  boot.kernelPackages = pkgs.linuxPackages_rpi4;

  boot.consoleLogLevel = lib.mkDefault 7;

  sdImage = {
    firmwareSize = 128;
    # This is a hack to avoid replicating config.txt from boot.loader.raspberryPi
    populateFirmwareCommands =
      "${config.system.build.installBootLoader} ${config.system.build.toplevel} -d ./firmware";
    # As the boot process is done entirely in the firmware partition.
    populateRootCommands = "";
  };

  # the installation media is also the installation target,
  # so we don't want to provide the installation configuration.nix.
  installer.cloneConfig = false;
}

```

**Comment by Robertof** [comment]
Thanks! I don't see any issue with your configs. I'll experiment with it this evening and let you know!

**Comment by Robertof** [comment]
Hey @ccamrobertson -- as promised, I've played around with the various configurations and made this repo Rpi 4 compatible! 🎉 

However, I was not able to reproduce your issue -- i.e., even using the config you gave me verbatim the build succeeded at the first try. Could there be something weird on the host OS, e.g. strange limits/extremely out-of-date Docker/not enough disk space? Note that it should also work on macOS as in theory Docker just [virtualizes](https://docs.docker.com/docker-for-mac/docker-toolbox/) a Linux distro to work on macOS, so it should work.

Feel free to pull this repo, change `rpi3` to `rpi4` in [`config/sd-image.nix`](config/sd-image.nix) and give it another shot.

Thanks!
Roberto

**Comment by ccamrobertson** [comment]
Fantastic; I cleaned up the repo, pulled and build worked perfectly on my Mac! I'm good to close if @dsferruzza is, thanks!

**Comment by Robertof** [comment]
Amazing, thanks for testing! Let me know if you have any issues on the RPi itself -- I've tried to include sane defaults sourced from various config that I found so that in theory everything should work, but obviously I couldn't test!

Thanks again for your help!

**Comment by dsferruzza** [comment]
Hi! Sorry for the delay. I retried today in RPi4 mode and I got 2 errors:

The first is because `qemu-user-static` is not available in the version `5.0.4` on Debian repos anymore.
I fixed this by bumping the requested version (hypothesis: this won't change the expect behavior here):

```diff
diff --git a/docker/docker-compose.emulation.yml b/docker/docker-compose.emulation.yml
index b5f7141..a940ac0 100644
--- a/docker/docker-compose.emulation.yml
+++ b/docker/docker-compose.emulation.yml
@@ -12,8 +12,8 @@ services:
     build:
       context: setup-qemu
       args:
-        QEMU_PKG_URL: "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_5.0-4_amd64.deb"
-        QEMU_PKG_HASH: "67504130c4f63371746deb91b01433af4644cfebaeaa3a120535c6f7e54f6dcd"
+        QEMU_PKG_URL: "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_5.0-5_amd64.deb"
+        QEMU_PKG_HASH: "3af4bfe2fa31f6cdceae01fb356c7e80d95cf213ce49fed53505a42fd2f0504f"
         IMAGE_BASE: $IMAGE_BASE
     privileged: true
   # Main container, requires no elevated privileges to run. Builds NixOS.
```

The second error is as follows (I just added `--show-trace` to the nix-build command):

```
$ ./run.sh up --force-recreate
detecting architecture...
 detected non-ARM architecture, enabling emulation
+ docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.emulation.yml up --force-recreate
Recreating docker_setup-qemu_1 ... done
Recreating docker_build-nixos_1 ... done
Recreating docker_cleanup-qemu_1 ... done
Attaching to docker_setup-qemu_1, docker_build-nixos_1, docker_cleanup-qemu_1
setup-qemu_1    | registering QEMU...
setup-qemu_1    | binfmt: detected x86 architecture, proceeding
setup-qemu_1    | binfmt: successfully registered /root/qemu-aarch64-static as an interpreter for aarch64
build-nixos_1   | waiting until QEMU container finishes...
build-nixos_1   | aarch64 runs!
setup-qemu_1    | done!
cleanup-qemu_1  | waiting until build is finished to clean QEMU up...
docker_setup-qemu_1 exited with code 0
build-nixos_1   | starting build
build-nixos_1   | warning: Nix search path entry '/build/config/sd-image.nix' does not exist, ignoring
cleanup-qemu_1  | listening on [::]:11111 ...
cleanup-qemu_1  | connect to [::ffff:172.18.0.2]:11111 from docker_build-nixos_1.docker_default:42659 ([::ffff:172.18.0.3]:42659)
cleanup-qemu_1  | build done
cleanup-qemu_1  | binfmt: detected x86 architecture, proceeding
cleanup-qemu_1  | binfmt: clearing existing entry for qemu-aarch64-docker-nixos
build-nixos_1   | error: while evaluating the attribute 'config' at /home/nixos/nixpkgs/nixos/lib/eval-config.nix:64:5:
build-nixos_1   | while evaluating the attribute 'config' at /home/nixos/nixpkgs/lib/modules.nix:96:25:
build-nixos_1   | while evaluating 'yieldConfig' at /home/nixos/nixpkgs/lib/modules.nix:83:29, called from /home/nixos/nixpkgs/lib/modules.nix:82:16:
build-nixos_1   | while evaluating 'mergeModules' at /home/nixos/nixpkgs/lib/modules.nix:233:26, called from /home/nixos/nixpkgs/lib/modules.nix:73:17:
build-nixos_1   | while evaluating 'mergeModules'' at /home/nixos/nixpkgs/lib/modules.nix:237:36, called from /home/nixos/nixpkgs/lib/modules.nix:234:5:
build-nixos_1   | while evaluating 'flip' at /home/nixos/nixpkgs/lib/trivial.nix:138:16, called from /home/nixos/nixpkgs/lib/modules.nix:280:6:
build-nixos_1   | while evaluating 'byName' at /home/nixos/nixpkgs/lib/modules.nix:260:25, called from /home/nixos/nixpkgs/lib/modules.nix:268:21:
build-nixos_1   | while evaluating 'reverseList' at /home/nixos/nixpkgs/lib/lists.nix:393:17, called from /home/nixos/nixpkgs/lib/modules.nix:73:38:
build-nixos_1   | while evaluating anonymous function at /home/nixos/nixpkgs/lib/modules.nix:167:37, called from /home/nixos/nixpkgs/lib/modules.nix:68:19:
build-nixos_1   | while evaluating 'filterModules' at /home/nixos/nixpkgs/lib/modules.nix:157:36, called from /home/nixos/nixpkgs/lib/modules.nix:168:7:
build-nixos_1   | while evaluating anonymous function at /home/nixos/nixpkgs/lib/modules.nix:161:31, called from undefined position:
build-nixos_1   | while evaluating 'loadModule' at /home/nixos/nixpkgs/lib/modules.nix:106:53, called from /home/nixos/nixpkgs/lib/modules.nix:144:22:
build-nixos_1   | while evaluating 'isFunction' at /home/nixos/nixpkgs/lib/trivial.nix:333:16, called from /home/nixos/nixpkgs/lib/modules.nix:107:12:
build-nixos_1   | while evaluating anonymous function at /home/nixos/nixpkgs/nixos/lib/from-env.nix:2:7, called from /home/nixos/nixpkgs/nixos/default.nix:1:19:
build-nixos_1   | file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/nixos/nixpkgs/nixos/default.nix:1:60
cleanup-qemu_1  | binfmt: cleanup done
docker_build-nixos_1 exited with code 1
docker_cleanup-qemu_1 exited with code 0
```

Any idea how to fix this?

**Comment by Robertof** [comment]
Hey @dsferruzza,

thanks for pointing out the QEMU issue! I'll work this evening towards using a better way to fetch QEMU 5 which doesn't vanish (well, that's what I was expecting of Debian mirrors).

For the other issue it looks like you don't have the `sd-image.nix` file in the `config` directory -- maybe you're still using the old `sd-card.nix`? I did revamp the whole thing when adding support for the Pi 4 so if you start from scratch it should work fine.

**Comment by dsferruzza** [comment]
OK so I took a bit of time to investigate and it was an issue related to the way Docker Toolbox works (through a VM) on Windows: if you try to mount a volume with a directory that is not in the C: drive, you have to do a bit of configuration on the VM's shared folders (see https://headsigned.com/posts/mounting-docker-volumes-with-docker-toolbox-for-windows/). That's why it would find anything in the `/build` directory.

Now that it is fixed, the build seems to run. I will keep you posted on if it boots on my RPi4!

**Comment by Robertof** [comment]
Woah, amazing work! I will make sure to add a note to the doc to Windows users. Cheers!

**Comment by dsferruzza** [comment]
Hi!
Everything seems to work now!
NixOS boots correctly on my RPi4 and I can SSH to it!
Thanks for your help!

---

I think I will try to play with it when I have a bit more time:
1. use a more recent kernel (I believe this is a WIP in the community and it will come to nixpkgs eventually?)
2. it appears on my screen that, when startup ends, autologin with user "nixos" is done; I guess it is intended when running an install disk, but not so much in this case (BTW why building a NixOS installer?)
3. find out what is included in the nix store and maybe how to shrink that a bit (I get a 2.7GB image; I suspect it embeds unnecessary stuff)
4. figure out how to mount the system partition in RO mode, and maybe also mount a TMPFS or something like that to ensure that:
    - nothing is modified at runtime
    - the SD card can live long
    - it is OK to just unplug the RPi

(not for every projects, of course; but sometimes there is no variable state to keep and flashing to update is OK)

**Comment by Robertof** [comment]
Hey David,

amazing news! Thanks for reporting back.

Regarding your points:

1. Yeah, for the RPi 4 this is an annoying problem. The reason should be that the required changes for a mainline kernel to boot are not yet in the official Linux kernel tree, thus there is the need to use the (older) patched one. I am not sure if this is applicable yet (especially with the super-latest kernel), but this should be an useful tracking issue which reports the mainlining efforts: https://github.com/lategoodbye/rpi-zero/issues/43
2. That should go away once you make a real configuration (using `nixos-generate-config`) and making sure to not include the installer config. Something like this: https://github.com/NixOS/nixpkgs/issues/63720#issuecomment-633322705
3. That's intended because the installation image includes loads of stuff which after the first rebuild and garbage collection is removed, so you'll end up with a much lighter image and RAM usage. See also:
   - https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/installation-device.nix
   - https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/base.nix
4. That's a great point and I'd be interested if you get to do more about this. You might also be interested in this blog post: https://grahamc.com/blog/erase-your-darlings

Cheers!

**Comment by Quadronick** [comment]
Got the same issue.
```
build-nixos_1   | building '/nix/store/bpw05y2rmb50vaf4irn8y95pvnciqarx-unit-script-wpa_supplicant-start.drv'...
build-nixos_1   | building '/nix/store/jdl33155s6ygv979vzgvqww0vn4cpp6i-xscreensaver.pam.drv'...
build-nixos_1   | building '/nix/store/0bn430za959cy4awkpqyh4sbwsvmvcqq-unit-wpa_supplicant.service.drv'...
build-nixos_1   | building '/nix/store/3xy8lknaq3gajk286l51yhzs35s2cbfg-system-units.drv'...
build-nixos_1   | building '/nix/store/krq4h4ffvbj0lfrxxmg0l8pbfx4jm5xq-etc.drv'...
build-nixos_1   | building '/nix/store/r2vf30f6k7kcl31ipjnvhwhw6k3drm77-nixos-system-nixos-20.09pre-git.drv'...
build-nixos_1   | building '/nix/store/8dw9naqd3fx06ny81y386l8cp6rvprm7-closure-info.drv'...
build-nixos_1   | building '/nix/store/sfqffx9kh1ghzq0bkp3z35013s4l1nd7-ext4-fs.img.zst.drv'...
build-nixos_1   | Preparing store paths for image...
build-nixos_1   | Creating an EXT4 image of 2793578496 bytes (numInodes=91988, numDataBlocks=498050)
build-nixos_1   | semop(1): encountered an error: Function not implemented
build-nixos_1   | builder for '/nix/store/sfqffx9kh1ghzq0bkp3z35013s4l1nd7-ext4-fs.img.zst.drv' failed with exit code 1
build-nixos_1   | cannot build derivation '/nix/store/ddf9l5yrk9lji8n2qnm02ws0kxclpr1l-nixos-sd-image-20.09pre-git-aarch64-linux.img.drv': 1 dependencies couldn't be built
build-nixos_1   | error: build of '/nix/store/ddf9l5yrk9lji8n2qnm02ws0kxclpr1l-nixos-sd-image-20.09pre-git-aarch64-linux.img.drv' failed
cleanup-qemu_1  | connect to [::ffff:172.18.0.2]:11111 from docker_build-nixos_1.docker_default:40641 ([::ffff:172.18.0.3]:40641)
cleanup-qemu_1  | build done
cleanup-qemu_1  | binfmt: detected x86 architecture, proceeding
cleanup-qemu_1  | binfmt: clearing existing entry for qemu-aarch64-docker-nixos
cleanup-qemu_1  | binfmt: cleanup done
docker_cleanup-qemu_1 exited with code 0
docker_build-nixos_1 exited with code 100
```
Args used:
        NIXPKGS_BRANCH: "master"
        APPLY_CPTOFS_PATCH: "y"
        DISABLE_ZFS_IN_INSTALLER: "y"

Build target: rpi4

**Comment by SuperCipher** [comment]
I have this problem #1 as well
mine was on macOS Catalina version 10.15.6 (19G2021) 
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build eefe0d31
I fix it by changing Docker resource config.

### Docker resource config
|build status| Build exited with code  | CPUs | Memory (GB) | Swap (GB) | Disk image size (GB)|
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| FAILING | 100  | 2  | 2 | 1 | 59.6 GB (15.3 GB used) |
| PASSING | 0  | 4 | 12.25 | 2.5 | 59.6 GB (15.3 GB used)|

This is quite excessive but it works and build time reduce significantly too.
<img width="1042" alt="Screen Shot 2020-09-12 at 4 29 40 PM" src="https://user-images.githubusercontent.com/6429197/92992445-332e1d80-f515-11ea-9ab2-bcc2ecf2ddf3.png">

**Comment by Robertof** [comment]
Hey @SuperCipher, thanks for your insights! I have added some more clarification in the README about this particular problem that should make sure no one ever gets stuck on it ever again.

Please feel free to reopen it or raise another one if anything similar appears, I’ll be happy to help.

Thanks!

**Comment by bensleveritt** [comment]
Just to say I encountered this today, and just bumping my Docker memory from 2 to 12GB worked nicely. Many thanks to @Robertof and @SuperCipher!
