### ISSUE TITLE
This project is lacking a license

### ISSUE THREAD

**Issue by maxhbr** [Robertof/nixos-docker-sd-image-builder#11]
A OSS license would make it open source and would clarify the terms under which it can be used

**Comment by Robertof** [comment]
Hey, thanks for reaching out! You're indeed correct.

I'll license this under the MIT license just now.

**Comment by Robertof** [comment]
Also I'll be happy to know if you're using it for something cool!

**Comment by maxhbr** [comment]
Thank you. Right now I just plan to try to get my RPi4 working. Later it probably will be my smart-home hub running deconz https://github.com/maxhbr/myconfig/blob/master/modules/service.deconz.nix.

**Comment by Robertof** [comment]
Sounds great! Feel free to reach out if you encounter any issue with this this repo, I'll be happy to help!

**Comment by maxhbr** [comment]
FYI: The PR 82718 on nixpkgs is already merged into master, see https://github.com/NixOS/nixpkgs/pull/82718. You might want to add a comment that `APPLY_CPTOFS_PATCH: "y"` can not be used together with `NIXPKGS_BRANCH: "master"`

**Comment by Robertof** [comment]
Hey, sorry for getting back this late -- lots of stuff came through that really limited my possibility to look into other stuff. I'll add a note to the documentation and also try to make the script resillient so that it doesn't fail if the patch is already applied.

Thanks for spotting this!
