### ISSUE TITLE
QEMU package is no longer available

### ISSUE THREAD

**Issue by Robertof** [Robertof/nixos-docker-sd-image-builder#2]
Debian has a new QEMU package and the old one is not available anymore. Find a way so that this doesn't happen anymore.

**Comment by Rodrigo-Barros** [comment]
> Debian has a new QEMU package and the old one is not available anymore. Find a way so that this doesn't happen anymore.

Hey I fix this by changing  these lines:

QEMU_PKG_URL: "http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_5.0-5_amd64.deb"
        QEMU_PKG_HASH: "3af4bfe2fa31f6cdceae01fb356c7e80d95cf213ce49fed53505a42fd2f0504f"

in docker/docker-compose.emulation.yml

**Comment by Robertof** [comment]
Thanks Rodrigo, appreciated! I will be looking for a permalink to the Debian archives so that if they update the package again it won't stop the container from working.

**Comment by Rodrigo-Barros** [comment]
It's always good receive a positive feedback, and you made a great job in this docker image.
I have a question to you when I have build my image some softwares was missing like nixos-install and nixos-rebuild, can you help me with this situation?

**Comment by Robertof** [comment]
Thanks!

Happy to help. Do you mean that you are missing these tools on your Raspberry Pi, or are you getting some errors at other stages? If you have a log or anything other which can be helpful to attach it would be great.

**Comment by Rodrigo-Barros** [comment]
Oops I forgot to specify where the error occurs, it is after logging into RaspeberryPI as you said, software like nixos-rebuild or nixos-install are not available.

<details>
<summary>build.log</summary>

```
# A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
  
detecting architecture...
 detected non-ARM architecture, enabling emulation
+ docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.emulation.yml up
Starting docker_setup-qemu_1 ... 
Starting docker_setup-qemu_1

Starting docker_setup-qemu_1 ... done
Starting docker_build-nixos_1 ... 
Starting docker_build-nixos_1

Starting docker_build-nixos_1 ... done
Starting docker_cleanup-qemu_1 ... 
Starting docker_cleanup-qemu_1

Starting docker_cleanup-qemu_1 ... done
Attaching to docker_setup-qemu_1, docker_build-nixos_1, docker_cleanup-qemu_1
setup-qemu_1    | registering QEMU...
build-nixos_1   | waiting until QEMU container finishes...
setup-qemu_1    | binfmt: detected x86 architecture, proceeding
cleanup-qemu_1  | waiting until build is finished to clean QEMU up...
build-nixos_1   | aarch64 runs!
cleanup-qemu_1  | listening on [::]:11111 ...
setup-qemu_1    | binfmt: successfully registered /root/qemu-aarch64-static as an interpreter for aarch64
build-nixos_1   | starting build
setup-qemu_1    | done!
docker_setup-qemu_1 exited with code 0
build-nixos_1   | /nix/store/ix5ygh90i6q4g2hvli3qghnybr1xbxh7-nixos-sd-image-20.03post-git-aarch64-linux.img
cleanup-qemu_1  | connect to [::ffff:172.19.0.2]:11111 from docker_build-nixos_1.docker_default:43781 ([::ffff:172.19.0.3]:43781)
cleanup-qemu_1  | build done
cleanup-qemu_1  | binfmt: detected x86 architecture, proceeding
cleanup-qemu_1  | binfmt: clearing existing entry for qemu-aarch64-docker-nixos
cleanup-qemu_1  | binfmt: cleanup done
docker_build-nixos_1 exited with code 0
docker_cleanup-qemu_1 exited with code 0
```
</details>

**Comment by Rodrigo-Barros** [comment]
Hey I rebuild the image again and now everything it's working as expected, thanks for your assistance and sorry for any inconvenience.

**Comment by Robertof** [comment]
Hey @Rodrigo-Barros, so sorry for the late response -- I was quite swamped up at work! I am happy that it worked out for you, the issue looked very weird indeed. It also shouldn't have required a rebuild of the image!
