### ISSUE TITLE
Not booting on 8GB RPi4

### ISSUE THREAD

**Issue by ajlennon** [Robertof/nixos-docker-sd-image-builder#20]
Hi,

Love the docker container idea. I switched the package branch to master and changed over to the ./rpi4 config

But when I write to SD card and boot I just get the boot colour screen

![image](https://user-images.githubusercontent.com/1537834/103489716-40498200-4e0e-11eb-93dd-2483d533a4d5.png)

I tried flashing both with etcher and dd..

Any advice? Thanks,

Alex

**Comment by Robertof** [comment]
Hey! Huge apologies for the delay in getting back to you -- this has been an incredibly busy period!

Did you manage to sort this out? This is weird, I'd expect the image to work on the Pi 4 with 8 gigs of RAM. Did you try the latest official unstable build from NixOS' hydra? If you could do that and ascertain that it works, we can see what we need to tweak to sort it out!

**Comment by luizirber** [comment]
[This comment][0] fixed the boot problem for me: add `8250.nr_uarts=1` to the cmdline/boot params.

[0]: https://github.com/NixOS/nixpkgs/pull/97883#issuecomment-757133139

**Comment by Robertof** [comment]
Excellent, thank you so much! I suppose adding it here will make the image work?

https://github.com/Robertof/nixos-docker-sd-image-builder/blob/03359cbe7114901abe4f935fc1e633d9c8746b8f/config/rpi4/default.nix#L25

**Comment by luizirber** [comment]
> Excellent, thank you so much! I suppose adding it here will make the image work?

In the end I changed a bit more to get the current nixpkgs `master` branch to compile:
```
  boot.kernelParams = [
    "console=tty1"
    "console=ttyAMA0,115200"
    "8250.nr_uarts=1"
  ];

  boot.initrd.availableKernelModules = [
    # Allows early (earlier) modesetting for the Raspberry Pi
    "vc4" "bcm2835_dma" "i2c_bcm2835"
  ];
```
I removed `cma=64M` (because it is also mentioned in that github issue as a problem), and fixed `avaliableKernelModules` because the base `aarch64` image sets some modules which are not available (which is the reason why the rpi4 image is not building in hydra: https://github.com/NixOS/nixpkgs/issues/111683)

**Comment by sciamp** [comment]
> > Excellent, thank you so much! I suppose adding it here will make the image work?
> 
> In the end I changed a bit more to get the current nixpkgs `master` branch to compile:
> 
> ```
>   boot.kernelParams = [
>     "console=tty1"
>     "console=ttyAMA0,115200"
>     "8250.nr_uarts=1"
>   ];
> 
>   boot.initrd.availableKernelModules = [
>     # Allows early (earlier) modesetting for the Raspberry Pi
>     "vc4" "bcm2835_dma" "i2c_bcm2835"
>   ];
> ```
> 
> I removed `cma=64M` (because it is also mentioned in that github issue as a problem), and fixed `avaliableKernelModules` because the base `aarch64` image sets some modules which are not available (which is the reason why the rpi4 image is not building in hydra: [NixOS/nixpkgs#111683](https://github.com/NixOS/nixpkgs/issues/111683))

removing `cma=64M` and adding `8250.nr_uarts=1` did the trick for my rpi4 (8GB)

thanks @luizirber !

and also many thanks to @Robertof for making this project 🙏🏻

**Comment by Robertof** [comment]
Thanks for the valuable feedback everyone! I'll proceed to upstream your suggested changes in the RPI 4 configuration, then close the PR. Feel free to reopen at any time if this issue reoccurs after I push the changes!
