### ISSUE TITLE
What to do with the working sd card

### ISSUE THREAD

**Issue by sergueif** [Robertof/nixos-docker-sd-image-builder#22]
Hi, it seems to have worked! I have the sd card running on a RPi3. Small request, do you mind a little paragraph in the Readme somewhere about what the next steps after are to use the system / grow it / add new packages. Just link to the appropriate guides. 

What I'm particularly confused by is:
- is what's running on this sd card the long-term nixos installation or is the sd card just an installer of sorts, so, first thing is to "install" the nixos on rPi? Kind of like most distros have a "LiveCD" which you use to install the long-term OS. Sorry, nixos newbie here
- I don't see any `/etc/nixos/configuration.nix` file on the running system after boot. Can I just add a new one from scratch? It would feel a lot easier if there was a starter file there to evolve from. This is partly what makes me suspect that I have to do some kind of further installation on this image after popping the sd card into rPi3.

Again, not asking to write a whole NixOS or Nix tutorial, just link to the 1-2 appropriate ones and clarify what it is exactly that's running after you pop the SD card in and what can I / should I do in it?

P.S. very exciting project. Can't wait to have a `.nix` file describing all the `smb` , `mpd` / etc. music / media center setup I want on my various computers at home so that I don't have to sit and configure them each time something goes wrong and I forget the configuration steps. Much appreciation for your project.

**Comment by arsfeld** [comment]
It's explained in the [README.md](https://github.com/Robertof/nixos-docker-sd-image-builder#raspberry-pi-3-and-4), basically once you boot NixOS, you can run those steps which will create a new "generation" in the same sdcard you used to boot. The NixOS generation you used to boot is still there and you generate a new one and switch to it, which will also be used in subsequent boots. 

Make sure to follow all instructions though, the boot configuration is **not** the same as you'll switch to, so if you make a mistake in the `/etc/nixos/configuration.nix` file you'll generate, you might have to re-flash your sdcard.

**Comment by sergueif** [comment]
ah thank you, I missed that section.

**Comment by Robertof** [comment]
Hey, sorry - just caught up to this! Thank you so much @arsfeld for taking the time to reply, and yes - there indeed are some indications on post-installation steps in the README, even though I get how you might have missed them!

Feel free to suggest any improvement.

Thank you for using this!
