### ISSUE TITLE
official images have SSH enabled now

### ISSUE THREAD

**Issue by edrex** [Robertof/nixos-docker-sd-image-builder#25]
https://github.com/NixOS/nixpkgs/pull/96991

Maybe add a note to the top of your blog and in the README so folks who just need SSH don't end up building their own images?

-- Best, Eric

**Comment by Robertof** [comment]
Hey! I'm aware that SSH is now enabled by default, but it doesn't have a default keypair nor a default password I believe - which makes this project still useful! 

I've started working on a side project a while ago to be able to change a prebuilt image file online to add a keypair, but that hasn't come to life yet. Feel free to correct me if I've got anything wrong!

**Comment by edrex** [comment]
I think the idea is that you would add your key to /root/.ssh/authorized_keys once the image is written to a block device. I'm concerned that new users will find your post indicating that ssh is disabled and get side tracked creating a custom image.

**Comment by Robertof** [comment]
Hey, apologies for the delay. You're absolutely right, I'll add a note here and in the blog post to make it clear!

**Comment by Robertof** [comment]
Blog post updated as well - thanks again!
