### ISSUE TITLE
How to get a desktop-environment in nixos to work with a raspberry-pi-4?

### ISSUE THREAD

**Issue by zeta-00** [Robertof/nixos-docker-sd-image-builder#26]
Hello @Robertof ,
After following these instructions to build nixos on a raspberry-pi-4:
https://gist.github.com/chrisanthropic/2e6d3645f20da8fd4c1f122113f89c06 ,
I was able to get nixos to build on the raspberry-pi-4 without any errors thrown, which is great.
But, whenever I enabled x-server, plasma5, and lightdm, it throws the error: `X11 server failed to start` and `display-manager.service failed to start`?
How do I troubleshoot this issue?
I'm sure others have ran into this same issue and fixed it, so if you know of any good nix documentation on how to fix this issue, then if you could please let me know.
Thanks in advance for the help, I think I'm close to getting nixos fully functional on my raspberry-pi-4, but I have to fix this issue to move forward.
If you require more information, then I can pastebin the logs that show the errors.

**Comment by Robertof** [comment]
Hey, thanks for reaching out.

Unfortunately I've never really ran a graphical environment on my Pi via Nix, so I don't think I will be able to give you any consistent help. If you already inspected the logs with `journalctl` (e.g. `journalctl`, `journalctl -u display-manager.service`) then I'm afraid you already did more than I would have suggested you!

You might want to reach out to [any of the NixOS communities](https://nixos.org/community/index.html), such as IRC or the official forums. I've asked questions before and everyone has been extremely kind.

Apologies for not being much of help - I will close this issue as it's not related to the SD image builder, but feel free to reach out if anything else goes wrong!

**Comment by zeta-00** [comment]
It turns out some extra drivers were, missing, they've recently added them now, so this issue should no longer persist with current nixos-pi-4 build-images.
