### ISSUE TITLE
Is there a way to add software to the generated image?

### ISSUE THREAD

**Issue by ri0t** [Robertof/nixos-docker-sd-image-builder#30]
I'm trying to generate "firmware"-SD card images with my own software preinstalled. Is there a way to customize the generated image to contain a set of packages along with their dependencies?

**Comment by ri0t** [comment]
Aah, i think i have it doing what i need :D :dancers:

**Comment by Chris2011** [comment]
Please share with the community how you did this. For example, I added my own config.nix with some stuff. What was your solution?

**Comment by Robertof** [comment]
Sorry for the late answer! See this issue which might provide some insight about the way things are: https://github.com/Robertof/nixos-docker-sd-image-builder/issues/9

If you just want to add software to the generated image (not the final installed system) you should be able to override `environment.systemPackages` in [`sd-image.nix`](https://github.com/Robertof/nixos-docker-sd-image-builder/blob/34788585786dfc4d075c2de7bcbd0185429ed505/config/sd-image.nix). The base list of packages you can draw your inspiration from is here: https://github.com/NixOS/nixpkgs/blob/d8807d2e2cd92c13f8b75a72f2d3143f65cc6812/nixos/modules/profiles/base.nix

**Comment by Chris2011** [comment]
I imported my own config from a git repo to add the software to the generated image. When I have a look into the *.img file all is there. So this works for me :).

**Comment by Robertof** [comment]
Closing this as I think you brilliantly solved the issue - thanks Chrizzly!
