### ISSUE TITLE
run.sh, connection refused. docker rootless ?

### ISSUE THREAD

**Issue by gl-yziquel** [Robertof/nixos-docker-sd-image-builder#32]
Hi.

I'm running docker rootless. I get the following:

```console
mini-me@virtucon ~/h/c/nixos-docker-sd-image-builder (master)> ./run.sh
detecting architecture...
detected non-ARM architecture, enabling emulation
figuring out if docker-compose >= 2.0.0 workaround is needed...
+ sudo docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.emulation.yml up
[sudo] password for mini-me:
WARNING: The IMAGE_BASE variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused
```

I suspect this is tied to me using docker rootless. Am I wrong ?

If I'm right, it would be nice to amend the README.

**Comment by gl-yziquel** [comment]
Removing the `sudo`in favour of only `docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.emulation.yml up` got me past this issue.

```console
mini-me@virtucon ~/h/c/nixos-docker-sd-image-builder (master) [1]> docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.emulation.yml up
WARNING: The IMAGE_BASE variable is not set. Defaulting to a blank string.
Creating network "docker_default" with the default driver
Building setup-qemu
[+] Building 12.2s (10/10) FINISHED docker:default 
 => [internal] load build definition from Dockerfile 0.2s 
 => => transferring dockerfile: 249B 0.0s 
 => [internal] load .dockerignore 0.2s 
 => => transferring context: 2B 0.0s 
 => [internal] load metadata for docker.io/library/alpine:latest 1.8s 
 => [internal] load build context 0.1s 
 => => transferring context: 4.31kB 0.0s 
 => [1/5] FROM docker.io/library/alpine:latest@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a 0.3s 
 => => resolve docker.io/library/alpine:latest@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a 0.1s 
 => => sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a 1.64kB / 1.64kB 0.0s 
 => => sha256:c5c5fda71656f28e49ac9c5416b3643eaa6a108a8093151d6d1afc9463be8e33 528B / 528B 0.0s 
 => => sha256:7e01a0d0a1dcd9e539f8e9bbd80106d59efbdf97293b3d38f5d7a34501526cdb 1.47kB / 1.47kB 0.0s 
 => [2/5] COPY build/ scripts/ /root/ 0.2s 
 => [3/5] WORKDIR /root 0.2s 
 => [4/5] RUN apk add dpkg curl 2.2s 
 => [5/5] RUN sh /root/setup-image.sh 6.4s 
 => exporting to image 0.8s 
 => => exporting layers 0.7s 
 => => writing image sha256:d6f47e183c1f25ca8d8b4bc59ef89094f182ee3fc8b540de51c2a7119f5541a1 0.0s 
 => => naming to docker.io/library/qemu-handler 0.0s 
WARNING: Image for service setup-qemu was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`. 
Building build-nixos
[+] Building 51.7s (15/15) FINISHED docker:default
 => [internal] load build definition from Dockerfile 0.1s 
 => => transferring dockerfile: 820B 0.0s 
 => [internal] load .dockerignore 0.2s 
 => => transferring context: 2B 0.0s 
 => [internal] load metadata for docker.io/library/alpine:latest 0.3s 
 => [internal] load build context 0.2s 
 => => transferring context: 11.16kB 0.0s 
 => CACHED [ 1/10] FROM docker.io/library/alpine:latest@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a 0.0s 
 => [ 2/10] RUN apk add curl git sudo patch xz 1.6s 
 => [ 3/10] RUN adduser -D nixos 0.7s 
 => [ 4/10] RUN mkdir -m 0755 /nix 0.6s 
 => [ 5/10] RUN chown nixos /nix 0.6s 
 => [ 6/10] RUN echo 'Set disable_coredump false' >> /etc/sudo.conf 0.7s 
 => [ 7/10] RUN echo -e 'nixos ALL=(ALL) ALL\nnixos ALL=(root) NOPASSWD: /bin/cp' >> /etc/sudoers 0.7s 
 => [ 8/10] COPY --chown=nixos:nixos *.sh /home/nixos/ 0.2s 
 => [ 9/10] COPY --chown=nixos:nixos aarch64-tester /home/nixos/ 0.2s 
 => [10/10] RUN sh $HOME/setup-image-user.sh 34.7s 
 => exporting to image 10.9s 
 => => exporting layers 10.8s 
 => => writing image sha256:ad2e0dfc8215e1b2c41d04ab841478ff1f07ab647e276c21b326828a7d97f4db 0.0s 
 => => naming to docker.io/library/docker_build-nixos 0.0s 
WARNING: Image for service build-nixos was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating docker_setup-qemu_1 ... done
Creating docker_build-nixos_1 ... done
Creating docker_cleanup-qemu_1 ... done
Attaching to docker_setup-qemu_1, docker_build-nixos_1, docker_cleanup-qemu_1
build-nixos_1   | waiting until QEMU container finishes...
cleanup-qemu_1  | waiting until build is finished to clean QEMU up...
setup-qemu_1    | registering QEMU...
setup-qemu_1    | binfmt: detected x86 architecture, proceeding
setup-qemu_1    | mount: permission denied (are you root?)
build-nixos_1   | ./aarch64-tester: line 1: syntax error: unexpected "("
cleanup-qemu_1  | listening on [::]:11111 ...
docker_setup-qemu_1 exited with code 1
build-nixos_1   | ./aarch64-tester: line 1: syntax error: unexpected "("
build-nixos_1   | ./aarch64-tester: line 1: syntax error: unexpected "("
build-nixos_1   | ./aarch64-tester: line 1: syntax error: unexpected "("
```

And then, I get these last three lines in a loop, and it fails...

**Comment by Robertof** [comment]
Hello! Thanks for trying this out. Unfortunately, setting up transparent emulation via QEMU requires privileged containers -- [this is mentioned in the Troubleshooting section](https://github.com/Robertof/nixos-docker-sd-image-builder#troubleshooting).

This is the part which requires privileged access to the host: https://github.com/Robertof/nixos-docker-sd-image-builder/blob/4b9a6dfe2a5233e66a9a6bca3ac9bc24558558b1/docker/setup-qemu/scripts/update-binfmt.sh#L30

See also: https://github.com/Robertof/nixos-docker-sd-image-builder/blob/4b9a6dfe2a5233e66a9a6bca3ac9bc24558558b1/docker/docker-compose.emulation.yml#L19

**Comment by Robertof** [comment]
I'm happy to clarify!

This container does *not* do cross compilation of NixOS from x86 to ARM, which wouldn't require privileged access per-se. This is because it has historically been finicky to do so within the Nix ecosystem.

The alternative to cross-compilation is emulation: we emulate ARM to execute ARM binaries on x86. QEMU contains an emulator that can be executed as a standalone binary, which is awesome, but doesn't solve the problem yet, because Nix doesn't know about this emulation layer, so it doesn't change the fact that you can't execute ARM binaries on x86.

What does make a difference, instead, is [binfmt_misc](https://en.wikipedia.org/wiki/Binfmt_misc). This is a kernel feature that allows to specify a custom handler to execute files of a certain type. This container sets up QEMU as a `binfmt_misc` handler for ARM binaries, so that QEMU is transparently invoked by the kernel every time Nix attempts to run one. The result is being able to build Nix for ARM even on x86 systems.

The problem with containers is that they don't have their own kernel -- the kernel stays the host kernel. So privileges are required in order to let the containers mess with the host kernel, which is normally a thing you don't want, but which is useful in this case.

Note that, again, this is only necessary because we want to emulate ARM transparently on x86. If you were building this on an ARM system, you wouldn't have this problem. Hope it makes sense!

**Comment by gl-yziquel** [comment]
It does make sense.

Never dived in binfmt_misc too much, though.

Question, though: would using a --vm switch on an LXC container instead of docker solve the issue with a QEMU arm OS being run ? Not sure about that, but it seems to me that it could work.

**Comment by Robertof** [comment]
If it spawns a separate VM with its own kernel, then yes, it would work. But obviously you wouldn't be able to use `docker-compose`, so you would have to rewrite the entire repo to make it work with LXD.

A potentially easier option could be to use `vagrant` or something similar to quickly spin up a Linux VM, install Docker into it, clone this repo, and run it. Not ideal but should work!

**Comment by gl-yziquel** [comment]
Thank you for your explanations.

I'm not sure I have much time to engage in that kind of work. But these informations are useful.
