### ISSUE TITLE
Changing DISABLE_ZFS_IN_INSTALLER doesn't take effect

### ISSUE THREAD

**Issue by caseyhoward** [Robertof/nixos-docker-sd-image-builder#4]
If I change the DISABLE_ZFS_IN_INSTALLER in the docker-compose.yml file after having ran `run.sh` once the setting doesn't take effect. For some reason it chooses not to rebuild the docker image. After running the clean up command everything worked.

```
./run.sh down --rmi all -v
```

Not that big of a deal, but I was a little confused as to why it kept trying to build zfs. Maybe the README should mention this.

**Comment by Robertof** [comment]
Hey Casey,

thank you! That looks weird to be fair, I thought that `docker-compose` would have been able to infer the necessity of a rebuild when changing a build argument.

I'll try to see if I can sort it out otherwise I'll add a note to the README. Thanks again!

**Comment by Robertof** [comment]
Update: apparently, that's expected behavior as `docker-compose` only builds if the built image doesn't already exist. Note though that you can use `--build` without having to remove everything from scratch.

Will update the docs!

**Comment by caseyhoward** [comment]
Awesome. Thanks!
