### ISSUE TITLE
Building image with a valid configuration.nix in it

### ISSUE THREAD

**Issue by nomelif** [Robertof/nixos-docker-sd-image-builder#7]
Hi. I am a bit of nixos noob (certainly not privy to how nixos on arm works)

I built an image for the raspberry pi 4 and assumed that there would be a `configuration.nix` on the board such that it could run `nixos-rebuild switch`. To my surprise, that was not the case. Is there a good reason as to why that is the case? Is it a mistake of mine?

If this is by design, what is the correct procedure to get a `configuration.nix` onto the board? Am I supposed to copy sd-card.nix?

**Comment by Robertof** [comment]
Hey @nomelif, sorry for the late response - was busy enjoying some space activity!

Anyway yes, that's intended! Let me explain better:

- the configuration that you see in the `config` directory of this repo is the _installer_ configuration, whose only purpose is to create an SD image with all the required software on it to boostrap NixOS on the target system. Note thought that it is, however, slightly different than the ISO images as you do not install NixOS on the medium where the ISO is stored at (which is usually a read-only CD), while you do with the SD image. 
- then there is the system configuration. NixOS allows you to generate a barebones version of this config using `nixos-generate-config`, you're free to customize that configuration as needed. However, don't forget to create an user (as the default `nixos` one will be deleted) with the relevant SSH keys and whatsoever.

There is an amazing tutorial written by @chrisanthropic which details better all of this and includes an example configuration for the Pi 4: https://gist.github.com/chrisanthropic/2e6d3645f20da8fd4c1f122113f89c06.

I'll probably amend the README in this repo to mention post-installation steps.

Hope everything is clear, thanks for reaching out!

**Comment by Robertof** [comment]
Wish granted! There are now detailed instructions in the README about [next steps](https://github.com/Robertof/nixos-docker-sd-image-builder#next-steps) after booting the SD image and example configurations for both the Pi 3 and Pi 4.

Let me know if you have any other issue, otherwise feel free to close this issue!

**Comment by nomelif** [comment]
Thank you very much.
